"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, BarChart3, Box, Check, ChevronRight, CircleDot, Compass, Copy, Download, Eye, FileAudio, FileText, Flame, FolderLock, LayoutDashboard, Play, Search, Settings, Sparkles, Target, Zap } from "lucide-react";
import { opportunities } from "@/lib/demo-data";
import { scoreOpportunity } from "@/lib/scoring";
import { getSupabaseBrowserClient } from "@/lib/supabase";
import type { Opportunity } from "@/lib/types";

const nav = [["Command Center", LayoutDashboard], ["Discover", Compass], ["Opportunities", Target], ["Product Studio", Box], ["Product Assets", FolderLock], ["Launch Packs", FileText], ["Analytics", BarChart3]] as const;
type View = (typeof nav)[number][0];

export default function Dashboard() {
  const [manualOpportunities, setManualOpportunities] = useState<Opportunity[]>([]);
  const ranked = useMemo<Opportunity[]>(() => [...opportunities, ...manualOpportunities].sort((a, b) => scoreOpportunity(b) - scoreOpportunity(a)), [manualOpportunities]);
  const [selected, setSelected] = useState(ranked[0].id);
  const [view, setView] = useState<View>("Command Center");
  const [scanState, setScanState] = useState<"idle" | "running" | "complete">("idle");
  const [charters, setCharters] = useState<Record<string, boolean>>({});
  const [launchPacks, setLaunchPacks] = useState<Record<string, boolean>>({});
  const [email, setEmail] = useState("");
  const [databaseState, setDatabaseState] = useState<"checking" | "not-configured" | "signed-out" | "ready" | "saving">("checking");
  const [databaseMessage, setDatabaseMessage] = useState("");
  const active = ranked.find((item) => item.id === selected)!;
  const runScan = () => { setView("Discover"); setScanState("running"); window.setTimeout(() => setScanState("complete"), 1200); };

  useEffect(() => {
    const supabase = getSupabaseBrowserClient();
    if (!supabase) { setDatabaseState("not-configured"); return; }
    supabase.auth.getUser().then(({ data }) => {
      setDatabaseState(data.user ? "ready" : "signed-out");
      if (data.user) setDatabaseMessage(`Connected as ${data.user.email ?? "Forge369 user"}`);
    });
  }, []);

  useEffect(() => {
    const saved = window.localStorage.getItem("forge369-manual-opportunities");
    if (saved) setManualOpportunities(JSON.parse(saved) as Opportunity[]);
  }, []);

  function addManualOpportunity(input: Pick<Opportunity, "title" | "audience" | "problem" | "format">) {
    const item: Opportunity = { id: `manual-${Date.now()}`, ...input, source: "Founder input", urgency: 7, demand: 7, willingness: 7, transformation: 8, competition: 6, reach: 7, feasibility: 8, expansion: 7, trend: "Emerging" };
    const next = [...manualOpportunities, item];
    setManualOpportunities(next);
    window.localStorage.setItem("forge369-manual-opportunities", JSON.stringify(next));
    setSelected(item.id);
  }

  async function sendMagicLink() {
    const supabase = getSupabaseBrowserClient();
    if (!supabase || !email.trim()) { setDatabaseMessage("Enter your email address to receive a secure sign-in link."); return; }
    const { error } = await supabase.auth.signInWithOtp({ email: email.trim(), options: { emailRedirectTo: window.location.origin } });
    setDatabaseMessage(error ? error.message : "Check your email for the secure Forge369 sign-in link.");
  }

  async function saveWorkspace() {
    const supabase = getSupabaseBrowserClient();
    if (!supabase) return;
    const { data: auth } = await supabase.auth.getUser();
    if (!auth.user) { setDatabaseState("signed-out"); return; }
    setDatabaseState("saving");
    const displayName = auth.user.email?.split("@")[0] ?? "Forge369 user";
    const { error: profileError } = await supabase.from("profiles").upsert({ id: auth.user.id, display_name: displayName });
    if (profileError) { setDatabaseState("ready"); setDatabaseMessage(profileError.message); return; }
    const { count, error: countError } = await supabase.from("opportunities").select("id", { count: "exact", head: true });
    if (countError) { setDatabaseState("ready"); setDatabaseMessage(countError.message); return; }
    if (!count) {
      const { error } = await supabase.from("opportunities").insert(ranked.map((item) => ({ owner_id: auth.user.id, title: item.title, audience: item.audience, problem: item.problem, recommended_format: item.format, source_label: item.source, status: "shortlisted", scores: { urgency: item.urgency, demand: item.demand, willingness: item.willingness, transformation: item.transformation, competition: item.competition, reach: item.reach, feasibility: item.feasibility, expansion: item.expansion }, total_score: scoreOpportunity(item) })));
      if (error) { setDatabaseState("ready"); setDatabaseMessage(error.message); return; }
    }
    setDatabaseState("ready"); setDatabaseMessage(count ? "Your workspace is already saved in Supabase." : "Saved your first three scored opportunities to Supabase.");
  }

  return <main className="shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Flame size={19} /></span><span>FORGE<span>369</span></span></div><p className="eyebrow">DIGITAL PRODUCT FOUNDRY</p><nav>{nav.map(([label, Icon]) => <button onClick={() => setView(label)} className={view === label ? "nav-item active" : "nav-item"} key={label}><Icon size={17} /> {label}{label === "Opportunities" && <span className="count">{ranked.length}</span>}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><Settings size={17} /> Settings</button><div className="profile"><div className="avatar">JS</div><div><strong>Jay Steenkamp</strong><span>Founder workspace</span></div></div></div></aside>
    <section className="workspace"><header><div><p className="eyebrow">FORGE369 MVP · DEMO MODE</p><h1>{view}</h1><p>Find demand. Forge value. Ship products.</p></div><button className="primary" onClick={runScan}><Sparkles size={17} /> Run discovery scan</button></header>
      <DatabasePanel state={databaseState} message={databaseMessage} email={email} setEmail={setEmail} onSignIn={sendMagicLink} onSave={saveWorkspace} />
      {view === "Command Center" && <CommandCenter ranked={ranked} selected={selected} setSelected={setSelected} active={active} setView={setView} runScan={runScan} charterCount={Object.keys(charters).length} launchCount={Object.keys(launchPacks).length} />}
      {view === "Discover" && <Discover scanState={scanState} runScan={runScan} onReview={() => setView("Opportunities")} onAdd={addManualOpportunity} />}
      {view === "Opportunities" && <Opportunities ranked={ranked} selected={selected} setSelected={setSelected} onBuild={() => setView("Product Studio")} />}
      {view === "Product Studio" && <ProductStudio active={active} charterReady={Boolean(charters[active.id])} setCharterReady={() => setCharters((current) => ({ ...current, [active.id]: true }))} onPackage={() => setView("Launch Packs")} onAssets={() => setView("Product Assets")} />}
      {view === "Product Assets" && <ProductAssets active={active} databaseState={databaseState} />}
      {view === "Launch Packs" && <LaunchPacks active={active} launchReady={Boolean(launchPacks[active.id])} setLaunchReady={() => setLaunchPacks((current) => ({ ...current, [active.id]: true }))} />}
      {view === "Analytics" && <Analytics />}</section></main>;
}

function CommandCenter({ ranked, selected, setSelected, active, setView, runScan, charterCount, launchCount }: { ranked: Opportunity[]; selected: string; setSelected: (id: string) => void; active: Opportunity; setView: (view: View) => void; runScan: () => void; charterCount: number; launchCount: number }) { return <><div className="signal-bar"><div><span className="live-dot" /> DISCOVERY ENGINE READY</div><p>Use the scanner to collect and score market signals.</p><button onClick={runScan}>Run scan <ArrowRight size={15} /></button></div><div className="metrics"><Metric label="Opportunities" value={String(ranked.length)} note="Ranked by Forge Score" icon={<Target />} /><Metric label="Average score" value="76" note="Strong potential" icon={<BarChart3 />} /><Metric label="In production" value={String(charterCount)} note={charterCount ? "Product charters created" : "No charter yet"} icon={<Zap />} /><Metric label="Launch packs" value={String(launchCount)} note={launchCount ? "Ready to refine" : "None generated yet"} icon={<Check />} /></div><div className="section-head"><div><p className="eyebrow">TODAY'S SHORTLIST</p><h2>Top profit pockets</h2></div><button onClick={() => setView("Opportunities")} className="text-button">View all opportunities <ChevronRight size={15} /></button></div><div className="content-grid"><div className="opportunity-list">{ranked.map((item, index) => <OpportunityCard key={item.id} item={item} index={index} selected={selected === item.id} onClick={() => setSelected(item.id)} />)}</div><OpportunityBrief active={active} onBuild={() => setView("Product Studio")} /></div><section className="pipeline"><div className="section-head"><div><p className="eyebrow">SELECTED BUILD</p><h2>{active.title}</h2></div><span className="status"><CircleDot size={14} /> {charterCount ? "In progress" : "Ready to architect"}</span></div><div className="steps">{["Validate", "Architect", "Research", "Create", "Polish", "Package"].map((step, index) => <div className={index === 0 || (index === 1 && charterCount) ? "step complete" : "step"} key={step}><span>{index === 0 || (index === 1 && charterCount) ? <Check size={14} /> : index + 1}</span><p>{step}</p></div>)}</div></section></>; }
function Discover({ scanState, runScan, onReview, onAdd }: { scanState: "idle" | "running" | "complete"; runScan: () => void; onReview: () => void; onAdd: (input: Pick<Opportunity, "title" | "audience" | "problem" | "format">) => void }) { const finished = scanState === "complete"; return <section className="workflow-card"><p className="eyebrow">STEP 01 · MARKET DISCOVERY</p><h2>Find evidence before you build</h2><p>Discovery is a two-part system: capture and validate demand signals now, then automate approved web sources once they are connected. Forge369 will not present simulated web data as live research.</p><div className="scan-panel"><Search size={24} /><div><strong>{scanState === "running" ? "Preparing a research workspace…" : finished ? "Research workspace ready for review" : "Start an evidence-led research pass"}</strong><span>{finished ? "Your shortlisted opportunities are ready for scoring and product selection." : "This MVP currently supports structured founder evidence and opportunity scoring."}</span></div>{scanState !== "running" && <button className="primary" onClick={runScan}>{finished ? "Refresh workspace" : "Start research pass"}</button>}</div><EvidenceCapture /><ManualIntake onAdd={onAdd} />{finished && <div className="result-list"><div><Check size={16} /> Capture a source URL, quoted problem, and buyer language below</div><div><Check size={16} /> Turn repeated signals into a scored opportunity</div><div><Check size={16} /> Select only the ideas with sufficient evidence to build</div><button className="primary" onClick={onReview}>Review scored opportunities <ArrowRight size={16} /></button></div>}</section>; }

function EvidenceCapture() { const [source, setSource] = useState(""); const [insight, setInsight] = useState(""); const [items, setItems] = useState<{ source: string; insight: string }[]>([]); function submit(event: React.FormEvent) { event.preventDefault(); if (!source.trim() || !insight.trim()) return; setItems((current) => [{ source: source.trim(), insight: insight.trim() }, ...current]); setSource(""); setInsight(""); } return <form className="evidence-form" onSubmit={submit}><div className="form-head"><div><p className="eyebrow">EVIDENCE INTAKE</p><h3>Capture a buyer signal</h3></div><span className="status"><CircleDot size={14} /> {items.length} signals logged</span></div><label>Source URL or platform<input value={source} onChange={(event) => setSource(event.target.value)} placeholder="e.g. Reddit, YouTube comments, Google search result" /></label><label>What is the buyer actually saying?<input value={insight} onChange={(event) => setInsight(event.target.value)} placeholder="Quote the pain point, objection, or desired outcome." /></label><button className="secondary" type="submit"><Check size={15} /> Log evidence</button>{items.length > 0 && <div className="evidence-log">{items.map((item, index) => <div key={`${item.source}-${index}`}><strong>{item.source}</strong><span>{item.insight}</span></div>)}</div>}</form>; }
function Opportunities({ ranked, selected, setSelected, onBuild }: { ranked: Opportunity[]; selected: string; setSelected: (id: string) => void; onBuild: () => void }) { const active = ranked.find((item) => item.id === selected)!; return <><div className="section-head"><div><p className="eyebrow">STEP 02 · DECIDE</p><h2>Ranked opportunities</h2></div><span className="status"><CircleDot size={14} /> Evidence review</span></div><div className="content-grid"><div className="opportunity-list">{ranked.map((item, index) => <OpportunityCard key={item.id} item={item} index={index} selected={selected === item.id} onClick={() => setSelected(item.id)} />)}</div><OpportunityBrief active={active} onBuild={onBuild} /></div></>; }
function ProductStudio({ active, charterReady, setCharterReady, onPackage, onAssets }: { active: Opportunity; charterReady: boolean; setCharterReady: (value: boolean) => void; onPackage: () => void; onAssets: () => void }) { return <section className="workflow-card"><p className="eyebrow">STEP 03 · PRODUCT STUDIO</p><h2>{active.title}</h2><p>Turn a validated opportunity into a defined product before generating assets.</p><div className="charter-grid"><div><span>Audience</span><strong>{active.audience}</strong></div><div><span>Core problem</span><strong>{active.problem}</strong></div><div><span>Recommended format</span><strong>{active.format}</strong></div><div><span>Target transformation</span><strong>From uncertainty to a clear, usable result.</strong></div></div>{!charterReady ? <button className="primary" onClick={() => setCharterReady(true)}><Sparkles size={17} /> Generate product charter</button> : <div className="success-panel"><Check size={19} /><div><strong>Product charter created</strong><span>Audience, outcome, product format and asset list are ready for production.</span></div><div className="studio-actions"><button className="secondary" onClick={onAssets}>Open product assets</button><button className="primary" onClick={onPackage}>Create launch pack <ArrowRight size={16} /></button></div></div>}</section>; }
const lucidAssets = [
  ["00_START_HERE.pdf", "Start here guide", "PDF · 4.5 KB"],
  ["01_The_Lucid_Threshold_Complete_Guide.pdf", "Complete celestial guide", "PDF · 584 KB"],
  ["02_The_28_Night_Guided_Journey.pdf", "28-night guided journey", "PDF · 7.2 KB"],
  ["03_Printable_Dream_Journal.pdf", "Printable dream journal", "PDF · 41 KB"],
  ["03B_Fillable_Digital_Dream_Journal.pdf", "Fillable digital journal", "PDF · 202 KB"],
  ["04_Reality_Check_and_Dream_Sign_Tracker.pdf", "Reality-check tracker", "PDF · 7.2 KB"],
  ["05_Bedside_Reference_Cards.pdf", "Bedside reference cards", "PDF · 3.3 KB"],
  ["07_Five_Minute_Relaxation_Audio.mp3", "Five-minute relaxation audio", "Audio · 6.9 MB"],
  ["08_First_Lucidity_Preparation_Audio.mp3", "First-lucidity preparation audio", "Audio · 5.5 MB"],
  ["09_Technique_Selection_Guide.pdf", "Technique selection guide", "PDF · 7.1 KB"],
  ["10_Difficult_Dream_and_False_Awakening_Guide.pdf", "Difficult-dream guidance", "PDF · 6 KB"],
] as const;

function ProductAssets({ active, databaseState }: { active: Opportunity; databaseState: "checking" | "not-configured" | "signed-out" | "ready" | "saving" }) {
  const [selectedAsset, setSelectedAsset] = useState(1);
  useEffect(() => setSelectedAsset(0), [active.id]);
  const isLucid = /lucid dream/i.test(active.title);
  const assets = isLucid ? lucidAssets : createDraftAssets(active);
  const asset = assets[Math.min(selectedAsset, assets.length - 1)];
  const secure = databaseState === "ready";
  return <section className="asset-vault"><div className="asset-hero"><div><p className="eyebrow">PRODUCT ASSETS · {isLucid ? "COMPLETE PACKAGE" : "DRAFT MANIFEST"}</p><h2>{isLucid ? "Your complete customer package" : active.title}</h2><p>{isLucid ? "One polished offer, eleven customer-facing assets, and a single delivery bundle prepared for release." : `Forge369 has created a product-specific asset manifest for ${active.audience.toLowerCase()}. Generate the files from this brief; it is not the Lucid Threshold package.`}</p><div className="asset-stats"><span><strong>{assets.length}</strong> assets</span><span><strong>{isLucid ? "13.2 MB" : "Draft"}</strong> package</span><span><strong>{isLucid ? "v1.0" : "v0.1"}</strong> release</span></div></div><div className="vault-mark"><FolderLock size={27} /><span>Private vault</span></div></div><div className="secure-notice"><FolderLock size={18} /><div><strong>{secure ? "Private asset vault connected" : isLucid ? "Assets staged for secure storage" : "This product does not have files yet"}</strong><span>{secure ? "Files can now be uploaded to your private Supabase bucket and delivered with controlled access." : isLucid ? "Your package is intentionally not published to this public repository or a public Vercel URL. Sign in when your email access is restored to upload it privately." : "The manifest is specific to this opportunity. Forge369 will generate and store the actual files after the product-creation engine is connected."}</span></div></div><div className="asset-layout"><div className="asset-list"><div className="asset-list-head"><span>{isLucid ? "Customer deliverables" : "Proposed deliverables"}</span><small>{assets.length} files</small></div>{assets.map(([name, label, meta], index) => <button className={selectedAsset === index ? "asset-row selected" : "asset-row"} onClick={() => setSelectedAsset(index)} key={name}>{name.endsWith(".mp3") ? <FileAudio size={18} /> : <FileText size={18} />}<div><strong>{label}</strong><span>{meta}</span></div>{isLucid ? <Check size={15} /> : <CircleDot size={15} />}</button>)}</div><aside className="asset-preview"><p className="eyebrow">ASSET PREVIEW</p>{asset[0].endsWith(".mp3") ? <FileAudio size={38} /> : <FileText size={38} />}<h3>{asset[1]}</h3><p>{asset[0]}</p><span className="asset-ready">{isLucid ? <><Check size={14} /> Staged and quality-checked</> : <><CircleDot size={14} /> Awaiting product generation</>}</span><button className="secondary full-width" disabled={!isLucid}><Eye size={15} /> {isLucid ? "Preview after secure upload" : "No file to preview yet"}</button><button className="primary full-width" disabled={!secure || !isLucid}><Download size={15} /> {isLucid && secure ? "Download secure asset" : "Secure download unavailable"}</button></aside></div></section>;
}

function createDraftAssets(active: Opportunity) { const slug = active.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); return [[`${slug}-core-guide.pdf`, "Core implementation guide", "PDF · queued"], [`${slug}-quick-start.pdf`, "Quick-start checklist", "PDF · queued"], [`${slug}-workbook.pdf`, "Action workbook", "PDF · queued"], [`${slug}-tracker.pdf`, "Progress tracker", "PDF · queued"], [`${slug}-customer-onboarding.pdf`, "Customer onboarding", "PDF · queued"]] as const; }

function LaunchPacks({ active, launchReady, setLaunchReady }: { active: Opportunity; launchReady: boolean; setLaunchReady: (value: boolean) => void }) {
  const [copied, setCopied] = useState(false);
  const pack = useMemo(() => createLaunchPack(active), [active]);
  function copyPack() { navigator.clipboard.writeText(pack.markdown).then(() => { setCopied(true); window.setTimeout(() => setCopied(false), 2000); }); }
  function downloadPack() { const blob = new Blob([pack.markdown], { type: "text/markdown;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${active.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}-launch-pack.md`; link.click(); URL.revokeObjectURL(url); }
  return <section className="workflow-card"><p className="eyebrow">STEP 04 · LAUNCH PACK</p><h2>Prepare a product for Whop</h2><p>Build delivery, sales copy and onboarding assets from the approved product charter.</p>{!launchReady ? <button className="primary" onClick={() => setLaunchReady(true)}><Play size={16} /> Build launch pack</button> : <><div className="pack-actions"><div><span className="status"><Check size={14} /> Launch pack generated</span><small>Ready to refine, copy into Whop, or download as an editable Markdown file.</small></div><div><button className="secondary" onClick={copyPack}><Copy size={15} /> {copied ? "Copied" : "Copy pack"}</button><button className="primary" onClick={downloadPack}><Download size={15} /> Download .md</button></div></div><div className="launch-output"><article><p className="eyebrow">PRODUCT POSITIONING</p><h3>{pack.productName}</h3><p className="launch-subtitle">{pack.promise}</p><dl><dt>For</dt><dd>{active.audience}</dd><dt>Format</dt><dd>{active.format}</dd><dt>Outcome</dt><dd>{pack.outcome}</dd></dl></article><article><p className="eyebrow">WHOP LISTING COPY</p><h3>{pack.headline}</h3><p>{pack.description}</p><h4>What they receive</h4><ul>{pack.deliverables.map((item) => <li key={item}>{item}</li>)}</ul></article><article><p className="eyebrow">OFFER + DELIVERY</p><h3>Suggested offer</h3><p><strong>Starter price:</strong> {pack.price}</p><p>{pack.offer}</p><h4>Customer onboarding</h4><ol>{pack.onboarding.map((item) => <li key={item}>{item}</li>)}</ol></article><article><p className="eyebrow">LAUNCH CHECKLIST</p><h3>Before you publish</h3><ul className="checklist">{pack.checklist.map((item) => <li key={item}><Check size={15} /> {item}</li>)}</ul></article></div></>}</section>;
}

function createLaunchPack(active: Opportunity) {
  const productName = active.title === "From Zero to Lucid Dreaming" || /lucid dream/i.test(active.title) ? "The Lucid Threshold" : active.title;
  const isLucid = /lucid dream/i.test(active.title);
  const promise = isLucid ? "A guided 28-night system to build dream recall, recognize dream signs, and practise lucid dreaming with care." : `A focused system that helps ${active.audience.toLowerCase()} move from a recurring problem to a clear, usable result.`;
  const outcome = isLucid ? "A calmer, repeatable lucid-dream practice built around consistency, not guarantees." : "A practical outcome the customer can apply immediately.";
  const headline = isLucid ? "Learn to recognize the moment you are dreaming." : `A practical path beyond ${active.problem.toLowerCase()}`;
  const description = isLucid ? "The Lucid Threshold is an immersive beginner guide for people who want to explore lucid dreaming without hype. It combines a 28-night guided journey, dream-journaling tools, reality-check training, pre-sleep relaxation, and first-lucidity support in one clear practice." : `${productName} turns a specific pain point into a guided, practical system. It is designed to be simple to start, useful from day one, and easy to follow through to a measurable outcome.`;
  const deliverables = isLucid ? ["Complete Lucid Threshold guide", "28-night guided journey", "Printable and fillable dream journal", "Reality-check and dream-sign tracker", "Bedside reference cards", "Five-minute relaxation and first-lucidity audio", "Difficult-dream and false-awakening guidance"] : ["Core implementation guide", "Action workbook or templates", "Quick-start checklist", "Progress tracker", "Customer onboarding instructions"];
  const price = isLucid ? "$37 introductory price, with a $57 anchor price after validation" : "$27–$47 introductory price, then raise after validated customer feedback";
  const offer = isLucid ? "A polished, self-guided digital experience for newcomers who want structure, practical tools, and a grounded approach to lucid dreaming." : `A complete ${active.format.toLowerCase()} designed to solve one clear problem without unnecessary complexity.`;
  const onboarding = isLucid ? ["Welcome the customer and set the expectation: consistency matters more than forcing results.", "Start Night 1 and set up the dream journal beside the bed.", "Use the daily reality-check tracker and five-minute wind-down routine.", "Follow the 28-night journey, then review dream signs and choose the next technique."] : ["Welcome the customer and explain the desired result.", "Direct them to the quick-start step.", "Set the first small action for day one.", "Invite feedback after their first result."];
  const checklist = ["Proofread the final guide and all downloadable assets", "Create a clean cover image and product thumbnail", "Upload files to the private delivery folder", "Paste the listing copy into Whop", "Set price, refund policy and customer-support email", "Run a test purchase and delivery check"];
  const markdown = `# ${productName} — Launch Pack\n\n## Positioning\n**For:** ${active.audience}\n\n**Format:** ${active.format}\n\n**Promise:** ${promise}\n\n**Outcome:** ${outcome}\n\n## Whop listing\n### ${headline}\n${description}\n\n### What customers receive\n${deliverables.map((item) => `- ${item}`).join("\n")}\n\n## Offer\n**Suggested price:** ${price}\n\n${offer}\n\n## Customer onboarding\n${onboarding.map((item, index) => `${index + 1}. ${item}`).join("\n")}\n\n## Before publishing\n${checklist.map((item) => `- [ ] ${item}`).join("\n")}\n`;
  return { productName, promise, outcome, headline, description, deliverables, price, offer, onboarding, checklist, markdown };
}
function ManualIntake({ onAdd }: { onAdd: (input: Pick<Opportunity, "title" | "audience" | "problem" | "format">) => void }) { const [title, setTitle] = useState(""); const [audience, setAudience] = useState(""); const [problem, setProblem] = useState(""); const [format, setFormat] = useState("Guide + templates"); const [saved, setSaved] = useState(false); function submit(event: React.FormEvent) { event.preventDefault(); if (!title.trim() || !audience.trim() || !problem.trim()) return; onAdd({ title: title.trim(), audience: audience.trim(), problem: problem.trim(), format }); setTitle(""); setAudience(""); setProblem(""); setSaved(true); window.setTimeout(() => setSaved(false), 2500); } return <form className="intake-form" onSubmit={submit}><div className="form-head"><div><p className="eyebrow">FOUNDER INPUT</p><h3>Add a profit pocket manually</h3></div>{saved && <span className="status"><Check size={14} /> Added and scored</span>}</div><label>Product idea<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. The Quiet Home Office System" /></label><label>Who needs it?<input value={audience} onChange={(event) => setAudience(event.target.value)} placeholder="e.g. Remote workers in noisy households" /></label><label>What painful problem does it solve?<textarea value={problem} onChange={(event) => setProblem(event.target.value)} placeholder="Describe the recurring frustration or desired outcome." /></label><label>Recommended format<select value={format} onChange={(event) => setFormat(event.target.value)}><option>Guide + templates</option><option>Workbook + tracker</option><option>Course + community</option><option>Toolkit + launch pack</option></select></label><button className="primary" type="submit">Add and score opportunity <ArrowRight size={16} /></button></form>; }
function Analytics() { return <section className="workflow-card"><p className="eyebrow">MEASURE WHAT WORKS</p><h2>Analytics will unlock after launch</h2><p>Once Whop and product analytics are connected, Forge369 will track conversion, refunds, completion, feedback and update opportunities.</p></section>; }
function OpportunityCard({ item, index, selected, onClick }: { item: Opportunity; index: number; selected: boolean; onClick: () => void }) { const score = scoreOpportunity(item); return <button onClick={onClick} className={selected ? "opportunity selected" : "opportunity"}><div className="rank">0{index + 1}</div><div className="opportunity-copy"><div className="tag-row"><span>{item.trend}</span><span>{item.source}</span></div><h3>{item.title}</h3><p>{item.problem}</p><small>{item.format}</small></div><div className="score"><strong>{score}</strong><span>/100</span></div></button>; }
function OpportunityBrief({ active, onBuild }: { active: Opportunity; onBuild: () => void }) { return <aside className="detail-card"><p className="eyebrow">OPPORTUNITY BRIEF</p><h2>{active.title}</h2><div className="detail-block"><span>Ideal customer</span><p>{active.audience}</p></div><div className="detail-block"><span>Problem worth solving</span><p>{active.problem}</p></div><div className="score-ring"><div><strong>{scoreOpportunity(active)}</strong><span>Forge Score</span></div></div><div className="mini-scores"><Mini label="Demand" value={active.demand} /><Mini label="Urgency" value={active.urgency} /><Mini label="Transformation" value={active.transformation} /><Mini label="Reach" value={active.reach} /></div><button className="primary full" onClick={onBuild}>Open in Product Studio <ArrowRight size={16} /></button></aside>; }
function Metric({ label, value, note, icon }: { label: string; value: string; note: string; icon: React.ReactNode }) { return <div className="metric"><div className="metric-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div>; }
function Mini({ label, value }: { label: string; value: number }) { return <div><span>{label}</span><div className="bar"><i style={{ width: `${value * 10}%` }} /></div><strong>{value}/10</strong></div>; }
function DatabasePanel({ state, message, email, setEmail, onSignIn, onSave }: { state: "checking" | "not-configured" | "signed-out" | "ready" | "saving"; message: string; email: string; setEmail: (email: string) => void; onSignIn: () => void; onSave: () => void }) {
  if (state === "checking") return <div className="database-panel"><span className="live-dot" /> Checking Forge369 database connection…</div>;
  if (state === "not-configured") return <div className="database-panel warning">Database variables are not available to this deployment yet. Redeploy after adding them in Vercel.</div>;
  if (state === "signed-out") return <div className="database-panel"><div><strong>Connect your Forge369 workspace</strong><span>Sign in securely to save opportunities and build products in Supabase.</span></div><input value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" type="email" /><button className="primary" onClick={onSignIn}>Send sign-in link</button>{message && <small>{message}</small>}</div>;
  return <div className="database-panel ready"><div><span className="live-dot" /><strong> Supabase connected</strong><small>{message || "Your private Forge369 workspace is ready to save."}</small></div><button className="primary" onClick={onSave} disabled={state === "saving"}>{state === "saving" ? "Saving…" : "Save workspace"}</button></div>;
}
