import type { Opportunity } from "./types";

export const opportunities: Opportunity[] = [
  {
    id: "lucid-threshold",
    title: "From Zero to Lucid Dreaming",
    audience: "Curious beginners who struggle to achieve their first lucid dream",
    problem: "Advice is fragmented, overly mystical or difficult to follow consistently.",
    format: "Guide + 28-night journey + journal + audio",
    source: "Creator insight",
    urgency: 7,
    demand: 9,
    willingness: 7,
    transformation: 9,
    competition: 6,
    reach: 8,
    feasibility: 9,
    expansion: 9,
    trend: "Stable",
  },
  {
    id: "home-office-focus",
    title: "The Quiet Home Office System",
    audience: "Remote workers with noisy households",
    problem: "Background noise and interruptions make meetings stressful and unprofessional.",
    format: "Setup playbook + buying guide + checklists",
    source: "Community pain signals",
    urgency: 8,
    demand: 8,
    willingness: 8,
    transformation: 8,
    competition: 7,
    reach: 8,
    feasibility: 9,
    expansion: 7,
    trend: "Rising",
  },
  {
    id: "family-meal-reset",
    title: "The 20-Minute Family Meal Reset",
    audience: "Busy parents who default to expensive takeout",
    problem: "Planning, shopping and cooking feel impossible after a full workday.",
    format: "Meal system + templates + shopping planner",
    source: "Search and social signals",
    urgency: 8,
    demand: 9,
    willingness: 7,
    transformation: 8,
    competition: 5,
    reach: 9,
    feasibility: 8,
    expansion: 8,
    trend: "Rising",
  },
];
